// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright the irlume contributors.

//! Landmark failure-mode probe (#276 stage 3): drive every landmark-consuming
//! cue with pathological geometry and record what each one answers.
//!
//! Why this exists: opening the detection/landmarks stage to third-party
//! models is gated on measuring what BAD landmarks do to the cues that consume
//! them, because a mis-indexed or garbage-emitting landmarker does not raise
//! an error, it produces confident numbers from the wrong pixels (the #25
//! relief work's chin-clamp incident is the worked example). This probe is
//! that measurement: synthetic frames, hand-built landmark pathologies, no
//! camera, deterministic, so the table it prints can be regenerated by anyone.
//!
//! The pathologies model real third-party failure classes, not fuzz:
//! - `swapped`     a model with a different left/right labeling convention
//! - `shifted`     landmarks locked onto background, off the face
//! - `offframe`    coordinates entirely outside the frame
//! - `far`         coordinates far beyond the frame (overflow-scale)
//! - `collapsed`   every point identical (a saturated/stuck output head)
//! - `nan`         non-finite outputs (a converted model with a broken op)
//! - `tiny`        a face box shrunk to a few pixels (bad detector scale)
//!
//! Usage: cargo run -p irlume-auth --example landmark_failure_probe
//!   [mesh.onnx]   (default models/face_landmark.onnx; section C is skipped
//!                  if the file is missing)

use irlume_auth::eye_glint;
use irlume_liveness::{detect_head_gesture, PoseSample};
use irlume_vision::align::{align_to_arcface, RgbView};
use irlume_vision::{head_pose, FaceMesh, Landmarks5};

const W: u32 = 400;
const H: u32 = 300;

/// Synthetic IR frame: gradient background, one bright disk per eye with a
/// one-pixel specular spike at each center, and a bright hotspot in the
/// top-left corner. The corner hotspot is the point of the exercise: Rust's
/// saturating float→int cast turns a NaN coordinate into pixel (0,0), so a
/// cue that samples there must be shown to find CONFIDENT bright pixels, not
/// zeros (emitter bloom at a frame edge is a realistic stand-in).
fn ir_frame() -> Vec<u8> {
    let mut g = vec![0u8; (W * H) as usize];
    for y in 0..H {
        for x in 0..W {
            g[(y * W + x) as usize] = 20 + (y * 60 / H) as u8;
        }
    }
    for (ex, ey) in [(120i32, 120i32), (200, 120)] {
        for dy in -6..=6 {
            for dx in -6..=6 {
                if dx * dx + dy * dy <= 36 {
                    let (x, y) = ((ex + dx) as u32, (ey + dy) as u32);
                    g[(y * W + x) as usize] = 230;
                }
            }
        }
        g[(ey as u32 * W + ex as u32) as usize] = 255;
    }
    for y in 0..8u32 {
        for x in 0..8u32 {
            g[(y * W + x) as usize] = 255;
        }
    }
    g
}

/// Mid-grey RGB frame with a brighter face-sized oval; content only matters in
/// that the mesh gets SOMETHING structured to run on.
fn rgb_frame() -> Vec<u8> {
    let mut d = vec![90u8; (W * H * 3) as usize];
    for y in 0..H {
        for x in 0..W {
            let (fx, fy) = (x as f32 - 160.0, y as f32 - 160.0);
            if (fx / 60.0).powi(2) + (fy / 80.0).powi(2) <= 1.0 {
                let i = ((y * W + x) * 3) as usize;
                d[i] = 180;
                d[i + 1] = 160;
                d[i + 2] = 150;
            }
        }
    }
    d
}

fn nominal5() -> Landmarks5 {
    [
        (120.0, 120.0),
        (200.0, 120.0),
        (160.0, 160.0),
        (130.0, 200.0),
        (190.0, 200.0),
    ]
}

fn pathologies5() -> Vec<(&'static str, Landmarks5)> {
    let n = nominal5();
    let shift = |l: Landmarks5, dx: f32, dy: f32| l.map(|(x, y)| (x + dx, y + dy));
    vec![
        ("nominal", n),
        ("swapped", [n[1], n[0], n[2], n[4], n[3]]),
        ("shifted", shift(n, 150.0, -90.0)),
        ("offframe", shift(n, -500.0, -500.0)),
        ("far", shift(n, 10_000.0, 10_000.0)),
        ("collapsed", [(160.0, 150.0); 5]),
        ("nan", [(f32::NAN, f32::NAN); 5]),
        (
            "tiny",
            [
                (159.0, 150.0),
                (161.0, 150.0),
                (160.0, 151.0),
                (159.5, 152.0),
                (160.5, 152.0),
            ],
        ),
    ]
}

fn fmt(v: f32) -> String {
    if v.is_nan() {
        "NaN".into()
    } else {
        format!("{v:.3}")
    }
}

fn main() {
    let ir = ir_frame();
    let rgb = rgb_frame();
    let view = RgbView {
        data: &rgb,
        width: W,
        height: H,
    };

    println!("## A. Five-point consumers (IR frame {W}x{H}, eye disks at (120,120)/(200,120), corner hotspot)\n");
    println!("| pathology | eye_glint | yaw_asym | pitch_frac | align_to_arcface |");
    println!("|---|---|---|---|---|");
    for (name, lm) in pathologies5() {
        let pose = head_pose(&lm);
        let align = match align_to_arcface(&view, &lm) {
            Ok(chip) => {
                // A chip of identical bytes is "aligned" garbage; say what came out.
                let (mn, mx) = chip
                    .iter()
                    .fold((255u8, 0u8), |(a, b), &v| (a.min(v), b.max(v)));
                format!("Ok (chip bytes {mn}..{mx})")
            }
            Err(e) => format!("Err ({e})"),
        };
        println!(
            "| {name} | {} | {} | {} | {align} |",
            fmt(eye_glint(&ir, W, H, &lm)),
            fmt(pose.yaw_asym),
            fmt(pose.pitch_frac),
        );
    }

    println!("\n## B. Head-pose stream consumer\n");
    let pose_stream = |p: Option<f32>| -> Vec<PoseSample> {
        (0..40)
            .map(|i| PoseSample {
                idx: i,
                pitch_frac: p,
                yaw_signed: p.map(|_| 0.0),
                bri: 120.0,
            })
            .collect()
    };
    println!(
        "- detect_head_gesture over pitch=NaN: **{:?}**  ·  over pitch=0.5 constant (degenerate-geometry default): **{:?}**",
        detect_head_gesture(&pose_stream(Some(f32::NAN))),
        detect_head_gesture(&pose_stream(Some(0.5))),
    );
    println!("\n## C. FaceMesh.landmarks() against pathological detector boxes\n");
    let mesh_path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "models/face_landmark.onnx".into());
    let Ok(mut mesh) = FaceMesh::load_from_file(&mesh_path) else {
        println!("(skipped: cannot load {mesh_path})");
        return;
    };
    println!("| bbox | result | finite | inside expanded crop | extent px |");
    println!("|---|---|---|---|---|");
    let boxes: Vec<(&str, [f32; 4])> = vec![
        ("nominal face", [100.0, 80.0, 220.0, 240.0]),
        ("zero-area", [160.0, 160.0, 160.0, 160.0]),
        ("inverted", [220.0, 240.0, 100.0, 80.0]),
        ("offframe", [-900.0, -900.0, -700.0, -700.0]),
        ("nan", [f32::NAN; 4]),
        ("huge", [-1e6, -1e6, 1e6, 1e6]),
    ];
    for (name, bbox) in &boxes {
        match mesh.landmarks(&view, bbox, 0.25) {
            Ok(lm) => {
                let finite = lm
                    .iter()
                    .filter(|(x, y)| x.is_finite() && y.is_finite())
                    .count();
                // The crop the mesh actually sampled, recomputed the same way.
                let (cx, cy) = ((bbox[0] + bbox[2]) * 0.5, (bbox[1] + bbox[3]) * 0.5);
                let half = 0.5 * (bbox[2] - bbox[0]).max(bbox[3] - bbox[1]) * 1.5;
                let inside = lm
                    .iter()
                    .filter(|(x, y)| {
                        (cx - half..=cx + half).contains(x) && (cy - half..=cy + half).contains(y)
                    })
                    .count();
                let (mut x0, mut y0, mut x1, mut y1) = (f32::MAX, f32::MAX, f32::MIN, f32::MIN);
                for &(x, y) in lm.iter().filter(|(x, y)| x.is_finite() && y.is_finite()) {
                    x0 = x0.min(x);
                    y0 = y0.min(y);
                    x1 = x1.max(x);
                    y1 = y1.max(y);
                }
                println!(
                    "| {name} | Ok ({} pts) | {finite}/{} | {inside}/{} | {} x {} |",
                    lm.len(),
                    lm.len(),
                    lm.len(),
                    fmt(x1 - x0),
                    fmt(y1 - y0),
                );
            }
            Err(e) => println!("| {name} | Err ({e}) | - | - | - |"),
        }
    }
}
