// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright the irlume contributors.

//! Landmark failure-mode probe (#276 stage 3): drive every landmark-consuming
//! cue with pathological geometry and record what each one answers.
//!
//! Why this exists: opening the detection/landmarks stage to third-party
//! models is gated on measuring what BAD landmarks do to the cues that consume
//! them, because a mis-indexed or garbage-emitting landmarker does not raise
//! an error, it produces confident numbers from the wrong pixels (the #25
//! relief work's chin-clamp incident is the worked example). This probe is
//! that measurement: synthetic frames, hand-built landmark pathologies, no
//! camera, deterministic, so the table it prints can be regenerated by anyone.
//!
//! The pathologies model real third-party failure classes, not fuzz:
//! - `swapped`     a model with a different left/right labeling convention
//! - `shifted`     landmarks locked onto background, off the face
//! - `offframe`    coordinates entirely outside the frame
//! - `far`         coordinates far beyond the frame (overflow-scale)
//! - `collapsed`   every point identical (a saturated/stuck output head)
//! - `nan`         non-finite outputs (a converted model with a broken op)
//! - `tiny`        a face box shrunk to a few pixels (bad detector scale)
//! - `mis-indexed` a 468-point set whose topology is rotated by one index
//!   (the Face Landmarker 478-point successor has a DIFFERENT point count, so
//!   an index-contract mismatch is exactly what a swap-in risks)
//!
//! Usage: cargo run -p irlume-auth --example landmark_failure_probe
//!   [mesh.onnx]   (default models/face_landmark.onnx; section D is skipped
//!                  if the file is missing)

use irlume_auth::{both_eyes_open, eye_glint, eye_glint_contrast};
use irlume_liveness::{
    calibrate_open_ear, detect_blink, detect_deliberate_closure, detect_nod, BlinkResult,
    ClosureCalibration, EarSample, PoseSample,
};
use irlume_vision::align::{align_to_arcface, RgbView};
use irlume_vision::{eye_ear, head_pose, FaceMesh, Landmarks5, EAR_LEFT};

const W: u32 = 400;
const H: u32 = 300;

/// Synthetic IR frame: gradient background, one bright disk per eye with a
/// one-pixel specular spike at each center, and a bright hotspot in the
/// top-left corner. The corner hotspot is the point of the exercise: Rust's
/// saturating float→int cast turns a NaN coordinate into pixel (0,0), so a
/// cue that samples there must be shown to find CONFIDENT bright pixels, not
/// zeros (emitter bloom at a frame edge is a realistic stand-in).
fn ir_frame() -> Vec<u8> {
    let mut g = vec![0u8; (W * H) as usize];
    for y in 0..H {
        for x in 0..W {
            g[(y * W + x) as usize] = 20 + (y * 60 / H) as u8;
        }
    }
    for (ex, ey) in [(120i32, 120i32), (200, 120)] {
        for dy in -6..=6 {
            for dx in -6..=6 {
                if dx * dx + dy * dy <= 36 {
                    let (x, y) = ((ex + dx) as u32, (ey + dy) as u32);
                    g[(y * W + x) as usize] = 230;
                }
            }
        }
        g[(ey as u32 * W + ex as u32) as usize] = 255;
    }
    for y in 0..8u32 {
        for x in 0..8u32 {
            g[(y * W + x) as usize] = 255;
        }
    }
    g
}

/// Mid-grey RGB frame with a brighter face-sized oval; content only matters in
/// that the mesh gets SOMETHING structured to run on.
fn rgb_frame() -> Vec<u8> {
    let mut d = vec![90u8; (W * H * 3) as usize];
    for y in 0..H {
        for x in 0..W {
            let (fx, fy) = (x as f32 - 160.0, y as f32 - 160.0);
            if (fx / 60.0).powi(2) + (fy / 80.0).powi(2) <= 1.0 {
                let i = ((y * W + x) * 3) as usize;
                d[i] = 180;
                d[i + 1] = 160;
                d[i + 2] = 150;
            }
        }
    }
    d
}

fn nominal5() -> Landmarks5 {
    [
        (120.0, 120.0),
        (200.0, 120.0),
        (160.0, 160.0),
        (130.0, 200.0),
        (190.0, 200.0),
    ]
}

fn pathologies5() -> Vec<(&'static str, Landmarks5)> {
    let n = nominal5();
    let shift = |l: Landmarks5, dx: f32, dy: f32| l.map(|(x, y)| (x + dx, y + dy));
    vec![
        ("nominal", n),
        ("swapped", [n[1], n[0], n[2], n[4], n[3]]),
        ("shifted", shift(n, 150.0, -90.0)),
        ("offframe", shift(n, -500.0, -500.0)),
        ("far", shift(n, 10_000.0, 10_000.0)),
        ("collapsed", [(160.0, 150.0); 5]),
        ("nan", [(f32::NAN, f32::NAN); 5]),
        (
            "tiny",
            [
                (159.0, 150.0),
                (161.0, 150.0),
                (160.0, 151.0),
                (159.5, 152.0),
                (160.5, 152.0),
            ],
        ),
    ]
}

/// A 468-point set whose EAR_LEFT hexagon is an open eye; everything else sits
/// at the face center. `rot` shifts every index by one, modeling a topology
/// whose point numbering does not match the shipped mesh's.
fn mesh468(open: bool, rot: bool) -> Vec<(f32, f32)> {
    let mut lm = vec![(160.0f32, 150.0f32); 468];
    let lid = if open { 2.0 } else { 0.2 };
    let hex = [
        (114.0, 120.0),
        (118.0, 120.0 - lid),
        (122.0, 120.0 - lid),
        (126.0, 120.0),
        (122.0, 120.0 + lid),
        (118.0, 120.0 + lid),
    ];
    for (k, p) in EAR_LEFT.iter().zip(hex) {
        lm[*k] = p;
    }
    if rot {
        lm.rotate_right(1);
    }
    lm
}

fn fmt(v: f32) -> String {
    if v.is_nan() {
        "NaN".into()
    } else {
        format!("{v:.3}")
    }
}

fn main() {
    let ir = ir_frame();
    let rgb = rgb_frame();
    let view = RgbView {
        data: &rgb,
        width: W,
        height: H,
    };

    println!("## A. Five-point consumers (IR frame {W}x{H}, eye disks at (120,120)/(200,120), corner hotspot)\n");
    println!("| pathology | eye_glint | glint_contrast | both_eyes_open | yaw_asym | pitch_frac | align_to_arcface |");
    println!("|---|---|---|---|---|---|---|");
    for (name, lm) in pathologies5() {
        let pose = head_pose(&lm);
        let align = match align_to_arcface(&view, &lm) {
            Ok(chip) => {
                // A chip of identical bytes is "aligned" garbage; say what came out.
                let (mn, mx) = chip
                    .iter()
                    .fold((255u8, 0u8), |(a, b), &v| (a.min(v), b.max(v)));
                format!("Ok (chip bytes {mn}..{mx})")
            }
            Err(e) => format!("Err ({e})"),
        };
        println!(
            "| {name} | {} | {} | {} | {} | {} | {align} |",
            fmt(eye_glint(&ir, W, H, &lm)),
            fmt(eye_glint_contrast(&ir, W, H, &lm)),
            both_eyes_open(&ir, W, H, &lm),
            fmt(pose.yaw_asym),
            fmt(pose.pitch_frac),
        );
    }

    println!("\n## B. eye_ear over a 468-point set (EAR_LEFT hexagon)\n");
    println!("| pathology | eye_ear(EAR_LEFT) |");
    println!("|---|---|");
    let ear_cases: Vec<(&str, Vec<(f32, f32)>)> = vec![
        ("open eye", mesh468(true, false)),
        ("closed eye", mesh468(false, false)),
        ("mis-indexed (rotated by 1)", mesh468(true, true)),
        ("collapsed", vec![(160.0, 150.0); 468]),
        ("nan", vec![(f32::NAN, f32::NAN); 468]),
        (
            "offframe",
            mesh468(true, false)
                .into_iter()
                .map(|(x, y)| (x - 500.0, y - 500.0))
                .collect(),
        ),
    ];
    for (name, lm) in &ear_cases {
        println!("| {name} | {} |", fmt(eye_ear(lm, &EAR_LEFT)));
    }

    println!("\n## C. Stream consumers (what a WINDOW of bad values decides)\n");
    let ear_stream = |ear: Option<f32>| -> Vec<EarSample> {
        (0..40)
            .map(|i| EarSample {
                idx: i,
                ear,
                bri: 120.0,
                cx: 160.0,
                cy: 150.0,
                fsize: 90.0,
                contrast: 40.0,
            })
            .collect()
    };
    let nan_ears = ear_stream(Some(f32::NAN));
    println!(
        "- detect_blink over 40 frames of EAR=NaN: **{:?}**",
        detect_blink(&nan_ears)
    );
    println!(
        "- calibrate_open_ear over 40 frames of EAR=NaN: **{:?}**",
        calibrate_open_ear(&nan_ears)
    );
    let cal = ClosureCalibration {
        ear_open: 0.30,
        ear_closed: 0.10,
    };
    println!(
        "- detect_deliberate_closure (valid calibration) over EAR=NaN: **{:?}**",
        detect_deliberate_closure(&nan_ears, &cal)
    );
    let pose_stream = |p: Option<f32>| -> Vec<PoseSample> {
        (0..40)
            .map(|i| PoseSample {
                idx: i,
                pitch_frac: p,
                yaw_signed: p.map(|_| 0.0),
                bri: 120.0,
            })
            .collect()
    };
    println!(
        "- detect_nod over pitch=NaN: **{:?}**  ·  over pitch=0.5 constant (degenerate-geometry default): **{:?}**",
        detect_nod(&pose_stream(Some(f32::NAN))),
        detect_nod(&pose_stream(Some(0.5))),
    );
    let is_blinked = matches!(detect_blink(&nan_ears), BlinkResult::Blinked);
    println!("- (NaN window read as a completed blink: {is_blinked})");
    // A mis-indexed topology reads EAR 0.0 forever (section B). The consent
    // gate compares EAR to an absolute per-user threshold, so the question a
    // stuck-closed signal poses is whether a WINDOW that never opens counts
    // as a deliberate closure.
    for stuck in [0.0f32, 0.05] {
        let s = ear_stream(Some(stuck));
        println!(
            "- detect_blink over EAR={stuck} constant (mis-indexed topology): **{:?}**  ·  \
             detect_deliberate_closure (valid calibration): **{:?}**",
            detect_blink(&s),
            detect_deliberate_closure(&s, &cal)
        );
    }

    println!("\n## D. FaceMesh.landmarks() against pathological detector boxes\n");
    let mesh_path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "models/face_landmark.onnx".into());
    let Ok(mut mesh) = FaceMesh::load_from_file(&mesh_path) else {
        println!("(skipped: cannot load {mesh_path})");
        return;
    };
    println!("| bbox | result | finite | inside expanded crop | extent px |");
    println!("|---|---|---|---|---|");
    let boxes: Vec<(&str, [f32; 4])> = vec![
        ("nominal face", [100.0, 80.0, 220.0, 240.0]),
        ("zero-area", [160.0, 160.0, 160.0, 160.0]),
        ("inverted", [220.0, 240.0, 100.0, 80.0]),
        ("offframe", [-900.0, -900.0, -700.0, -700.0]),
        ("nan", [f32::NAN; 4]),
        ("huge", [-1e6, -1e6, 1e6, 1e6]),
    ];
    for (name, bbox) in &boxes {
        match mesh.landmarks(&view, bbox, 0.25) {
            Ok(lm) => {
                let finite = lm
                    .iter()
                    .filter(|(x, y)| x.is_finite() && y.is_finite())
                    .count();
                // The crop the mesh actually sampled, recomputed the same way.
                let (cx, cy) = ((bbox[0] + bbox[2]) * 0.5, (bbox[1] + bbox[3]) * 0.5);
                let half = 0.5 * (bbox[2] - bbox[0]).max(bbox[3] - bbox[1]) * 1.5;
                let inside = lm
                    .iter()
                    .filter(|(x, y)| {
                        (cx - half..=cx + half).contains(x) && (cy - half..=cy + half).contains(y)
                    })
                    .count();
                let (mut x0, mut y0, mut x1, mut y1) = (f32::MAX, f32::MAX, f32::MIN, f32::MIN);
                for &(x, y) in lm.iter().filter(|(x, y)| x.is_finite() && y.is_finite()) {
                    x0 = x0.min(x);
                    y0 = y0.min(y);
                    x1 = x1.max(x);
                    y1 = y1.max(y);
                }
                println!(
                    "| {name} | Ok ({} pts) | {finite}/{} | {inside}/{} | {} x {} |",
                    lm.len(),
                    lm.len(),
                    lm.len(),
                    fmt(x1 - x0),
                    fmt(y1 - y0),
                );
            }
            Err(e) => println!("| {name} | Err ({e}) | - | - | - |"),
        }
    }
}
