#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright the irlume contributors.

"""Generate docs/HARDWARE.md from measured evidence, never by hand.

The competitor survey (docs/research/2026-08-24-face-unlock-competitor-
pain-survey.md) recorded that both Howdy's and visage's hardware-compat
pages rotted within months because they were maintained by hand. This
generator is the countermeasure: the matrix is RENDERED from two inputs
that already have review pressure on them:

1. docs/hardware/fleet-evidence.json — one record per validated host,
   each row citing the irlume version and the measurement that produced
   it. A camera without evidence does not get a row.
2. crates/irlume-camera/src/ir_emitter.rs — the `known_control` match
   arms, read straight from source so the emitter-control table in the
   docs can never drift from the code that applies it.

Community reports extend the JSON by PR with their evidence attached;
the generator merges nothing from thin air.

Usage: python3 scripts/generate-hardware-matrix.py
Writes docs/HARDWARE.md. CI-parity check: run with --check to exit 1
when the committed file differs from what the inputs would render (same
pattern as cargo fmt --check).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EVIDENCE = REPO / "docs/hardware/fleet-evidence.json"
OUT = REPO / "docs/HARDWARE.md"
EMITTER_SRC = REPO / "crates/irlume-camera/src/ir_emitter.rs"

HEADER = """\
# Hardware compatibility

> This page is GENERATED by `scripts/generate-hardware-matrix.py` from
> `docs/hardware/fleet-evidence.json` and the `known_control` table in
> `crates/irlume-camera/src/ir_emitter.rs`. Edit those, not this file.
> Every row cites the irlume version and the measurement that produced
> it; a camera without measured evidence does not get a row.

Howdy-class install pain (54% of its open issues) does not exist here:
no interpreter, no pip, no dlib. If your camera is not listed, irlume
still runs — the RGB path needs any UVC camera, and unknown IR emitters
take `sudo irlume ir-setup` (it measures, warns, and undoes; it never
blind-writes). Hardware reports are the most useful contribution:
open an issue with `irlume status`, `sudo irlume doctor --probe`, and
`irlume camera diagnostics --json` output attached.

## Validated hosts

"""


def known_control_entries() -> list[dict[str, str]]:
    """Parse the known_control match arms out of ir_emitter.rs.

    Line-oriented on purpose: the table is small, arms are one per USB
    identity, and each arm is preceded by a `//` comment naming the module.
    """
    lines = EMITTER_SRC.read_text(encoding="utf-8").splitlines()
    # Slice from the fn to the first `_ =>` after it.
    start = next(
        (i for i, l in enumerate(lines) if "fn known_control(vid: u16, pid: u16)" in l),
        None,
    )
    if start is None:
        raise SystemExit("could not locate known_control in ir_emitter.rs")
    end = next(
        (i for i in range(start, len(lines)) if lines[i].strip().startswith("_ =>")),
        None,
    )
    if end is None:
        raise SystemExit("could not find the table terminator in known_control")
    body = lines[start:end]

    arm_re = re.compile(
        r"^\((0x[0-9a-fA-F]{4}),\s*(0x[0-9a-fA-F]{4})\)\s*=>\s*Some\(EmitterControl"
    )
    unit_re = re.compile(r"unit:\s*(\d+)")
    entries: list[dict[str, str]] = []
    comment_first = ""
    i = 0
    while i < len(body):
        stripped = body[i].strip()
        if stripped.startswith("//"):
            # First line of a comment block names the module; later lines
            # carry caveats that stay in the source.
            if not comment_first:
                comment_first = stripped.lstrip("/ ")
        elif (m := arm_re.match(stripped)) :
            # The unit may sit on this line or the next couple.
            unit = ""
            for j in range(i, min(i + 3, len(body))):
                if um := unit_re.search(body[j]):
                    unit = um.group(1)
                    break
            entries.append(
                {
                    "vid": m.group(1)[2:].lower(),
                    "pid": m.group(2)[2:].lower(),
                    "unit": unit,
                    "comment": comment_first,
                }
            )
            comment_first = ""
        i += 1
    if not entries:
        raise SystemExit("parsed zero known_control arms; parser rot")
    return entries


def render_host(h: dict) -> list[str]:
    lines = []
    usb = h["usb"]
    ident = f"{usb['vid']}:{usb['pid']}"
    lines.append(f"### {h['host_label']}")
    lines.append("")
    lines.append(f"- **Module:** {h['module']} (`{ident}`)")
    rgb = h.get("rgb")
    if rgb:
        lines.append(
            f"- **RGB:** `/dev/{rgb['node']}` — {rgb['format']} ({rgb['role']})"
        )
    ir = h.get("ir")
    if ir:
        lines.append(f"- **IR:** `/dev/{ir['node']}` — {ir['format']}")
    else:
        lines.append("- **IR:** none (RGB-only host; convenience tier only)")
    lines.append(f"- **Capture mode:** {h['capture_mode']} — {h['capture_mode_source']}")
    em = h.get("emitter")
    if em:
        lines.append(
            f"- **IR emitter:** {em['control']} — {em['status']}"
            + (f". {em['notes']}" if em.get("notes") else "")
        )
    if h.get("pad"):
        lines.append(f"- **Anti-spoofing:** {h['pad']}")
    ev = h.get("evidence", {})
    if ev.get("irlume"):
        lines.append(f"- **Evidence (irlume {ev['irlume']}):**")
    else:
        lines.append("- **Evidence:**")
    for k, v in ev.items():
        if k == "irlume":
            continue
        lines.append(f"  - {k}: {v}")
    lines.append("")
    return lines


def main() -> int:
    data = json.loads(EVIDENCE.read_text(encoding="utf-8"))
    out = [HEADER]
    for h in data["hosts"]:
        out.extend(render_host(h))

    out.append("## Built-in IR emitter controls (`known_control`)\n")
    out.append(
        "Read from source at generation time. These are the modules whose"
        " emitter payload was validated end to end (write, read-back, optical"
        " output, restoration). Everything else uses `irlume ir-setup`.\n"
    )
    for e in known_control_entries():
        note = f" — {e['comment']}" if e["comment"] else ""
        out.append(
            f"- `{e['vid']}:{e['pid']}` MS-XU unit {e['unit']}, selector 0x06"
            f" (face authentication){note}"
        )
    out.append("")
    out.append(
        f"<!-- generated: schema {data['schema']}; inputs: docs/hardware/fleet-evidence.json + ir_emitter.rs known_control; regenerate with scripts/generate-hardware-matrix.py -->"
    )
    text = "\n".join(out) + "\n"

    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("HARDWARE.md is stale; regenerate with", sys.argv[0])
            return 1
        print("HARDWARE.md up to date")
        return 0

    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(data['hosts'])} hosts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
