// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright the irlume contributors.
//
// GENERATED FILE - DO NOT EDIT.
// Generated by benchmarks/preprocessing-conformance/gen_pad_vit_fixtures.py
// (sha256 c099586dd4ce00d972bb150879ff02f86cf3a6a4e2df3fc4defddfc25764453e). Regenerate with that script and re-review any diff.
//
// Oracle environment: cv2 5.0.0 (opencv-python 5.0.0.93), NumPy 2.5.2,
// Python 3.14.7 on Linux x86_64; cv2 threads=1, optimized dispatch/OpenCL/IPP
// disabled.
// Contract: recorded scorer m96 integer crop (immutable scorer source at
// 6ee8ef5c) + RGB8 cv2.resize INTER_LINEAR, normalized (px/255-0.5)/0.5.
// Each FIXTURES case pins the exact crop bounds, the exact 224x224x3 RGB8
// resize output (FNV-1a-64 + probe pixels), the exact float32 CHW tensor
// (FNV-1a-64 of its little-endian bytes) and float32 tensor probe values.
// CROP_FIXTURES pin float32 m96 bounds that float64 arithmetic misses.
// SCORER_WRAP_CASES are boxes whose scorer slice wraps to a non-empty chip.

use super::pad_vit_input_tests::Recipe;

pub(super) struct Fixture {
    pub name: &'static str,
    pub recipe: Recipe,
    pub bbox: [f32; 4],
    /// Half-open [x1, y1, x2, y2].
    pub crop: [i32; 4],
    /// FNV-1a-64 of the 224*224*3 RGB8 resize output.
    pub rgb8_fnv1a64: u64,
    /// FNV-1a-64 of the 3*224*224 float32 CHW tensor, little-endian.
    pub tensor_fnv1a64: u64,
    /// (x, y, [r, g, b]) probes of the RGB8 resize output.
    pub probes: &'static [(u16, u16, [u8; 3])],
    /// (plane, y, x, normalized value) probes.
    pub tensor_probes: &'static [(u8, u16, u16, f32)],
}

pub(super) const FIXTURES: &[Fixture] = &[
    Fixture {
        name: "ramp32_rounding_counterexample",
        recipe: Recipe::Ramp32,
        bbox: [0.0, 0.0, 32.0, 32.0],
        crop: [0, 0, 32, 32],
        rgb8_fnv1a64: 0xC7686AD853A0D385,
        tensor_fnv1a64: 0xE857A07E501474B7,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [248, 0, 124]), (0, 223, [0, 248, 124]), (223, 223, [248, 248, 248]), (112, 112, [124, 124, 124]), (4, 0, [1, 0, 0]), (223, 112, [248, 124, 186]), (112, 223, [124, 248, 186])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, 0.94509804f32), (0, 112, 112, -0.027450979f32), (1, 0, 0, -1.0f32), (1, 223, 223, 0.94509804f32), (1, 112, 112, -0.027450979f32), (2, 0, 0, -1.0f32), (2, 223, 223, 0.94509804f32), (2, 112, 112, -0.027450979f32)],
    },
    Fixture {
        name: "black_roi_white_outside",
        recipe: Recipe::White64BlackRoi,
        bbox: [24.0, 24.0, 31.0, 31.0],
        crop: [18, 18, 37, 37],
        rgb8_fnv1a64: 0x5320CFD53FC21325,
        tensor_fnv1a64: 0x94F33ECC517A0325,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [0, 0, 0]), (0, 223, [0, 0, 0]), (223, 223, [0, 0, 0]), (112, 112, [0, 0, 0]), (4, 0, [0, 0, 0]), (223, 112, [0, 0, 0]), (112, 223, [0, 0, 0])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, -1.0f32), (0, 112, 112, -1.0f32), (1, 0, 0, -1.0f32), (1, 223, 223, -1.0f32), (1, 112, 112, -1.0f32), (2, 0, 0, -1.0f32), (2, 223, 223, -1.0f32), (2, 112, 112, -1.0f32)],
    },
    Fixture {
        name: "full_frame_last_row_col",
        recipe: Recipe::Grid48x40,
        bbox: [0.0, 0.0, 48.0, 40.0],
        crop: [0, 0, 48, 40],
        rgb8_fnv1a64: 0xEF17CB2C3B741514,
        tensor_fnv1a64: 0xCFC282CBF49C2316,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [47, 0, 47]), (0, 223, [0, 39, 39]), (223, 223, [47, 39, 86]), (112, 112, [23, 20, 43]), (4, 0, [0, 0, 0]), (223, 112, [47, 20, 66]), (112, 223, [23, 39, 62])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, -0.6313726f32), (0, 112, 112, -0.81960785f32), (1, 0, 0, -1.0f32), (1, 223, 223, -0.69411767f32), (1, 112, 112, -0.84313726f32), (2, 0, 0, -1.0f32), (2, 223, 223, -0.32549018f32), (2, 112, 112, -0.6627451f32)],
    },
    Fixture {
        name: "fractional_interior",
        recipe: Recipe::Wide,
        bbox: [100.25, 40.5, 121.75, 57.25],
        crop: [81, 26, 140, 71],
        rgb8_fnv1a64: 0x257437DE1B1E7D11,
        tensor_fnv1a64: 0x7C54DF6C0148BF3D,
        probes: &[(0, 0, [81, 52, 107]), (223, 0, [139, 52, 165]), (0, 223, [81, 140, 151]), (223, 223, [139, 140, 209]), (112, 112, [110, 96, 158]), (4, 0, [82, 52, 108]), (223, 112, [139, 96, 187]), (112, 223, [110, 140, 180])],
        tensor_probes: &[(0, 0, 0, -0.36470586f32), (0, 223, 223, 0.09019613f32), (0, 112, 112, -0.1372549f32), (1, 0, 0, -0.5921569f32), (1, 223, 223, 0.09803927f32), (1, 112, 112, -0.24705881f32), (2, 0, 0, -0.1607843f32), (2, 223, 223, 0.6392157f32), (2, 112, 112, 0.23921573f32)],
    },
    Fixture {
        name: "negative_clipped",
        recipe: Recipe::Wide,
        bbox: [-2.5, -1.25, 18.5, 15.25],
        crop: [0, 0, 36, 29],
        rgb8_fnv1a64: 0xB08F1F2B3CA3CC38,
        tensor_fnv1a64: 0x462DA2D875E05E7F,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [35, 0, 35]), (0, 223, [0, 56, 28]), (223, 223, [35, 56, 63]), (112, 112, [17, 28, 32]), (4, 0, [0, 0, 0]), (223, 112, [35, 28, 49]), (112, 223, [17, 56, 45])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, -0.7254902f32), (0, 112, 112, -0.8666667f32), (1, 0, 0, -1.0f32), (1, 223, 223, -0.56078434f32), (1, 112, 112, -0.78039217f32), (2, 0, 0, -1.0f32), (2, 223, 223, -0.5058824f32), (2, 112, 112, -0.7490196f32)],
    },
    Fixture {
        name: "right_bottom_clipped",
        recipe: Recipe::Wide,
        bbox: [240.0, 116.0, 260.0, 134.0],
        crop: [222, 100, 256, 128],
        rgb8_fnv1a64: 0x47B1B99CB5937B9B,
        tensor_fnv1a64: 0x4BA9AAEC22D851E6,
        probes: &[(0, 0, [222, 200, 66]), (223, 0, [255, 200, 99]), (0, 223, [222, 254, 93]), (223, 223, [255, 254, 126]), (112, 112, [238, 227, 96]), (4, 0, [222, 200, 66]), (223, 112, [255, 227, 113]), (112, 223, [238, 254, 109])],
        tensor_probes: &[(0, 0, 0, 0.7411765f32), (0, 223, 223, 1.0f32), (0, 112, 112, 0.8666667f32), (1, 0, 0, 0.5686275f32), (1, 223, 223, 0.99215686f32), (1, 112, 112, 0.78039217f32), (2, 0, 0, -0.4823529f32), (2, 223, 223, -0.011764705f32), (2, 112, 112, -0.24705881f32)],
    },
    Fixture {
        name: "one_pixel_strip",
        recipe: Recipe::Wide,
        bbox: [32.0, 20.0, 32.1, 44.0],
        crop: [31, 0, 32, 64],
        rgb8_fnv1a64: 0x0C5AE02B4A6E4AA5,
        tensor_fnv1a64: 0x566E9EA8566978E5,
        probes: &[(0, 0, [31, 0, 31]), (223, 0, [31, 0, 31]), (0, 223, [31, 126, 94]), (223, 223, [31, 126, 94]), (112, 112, [31, 63, 63]), (4, 0, [31, 0, 31]), (223, 112, [31, 63, 63]), (112, 223, [31, 126, 94])],
        tensor_probes: &[(0, 0, 0, -0.75686276f32), (0, 223, 223, -0.75686276f32), (0, 112, 112, -0.75686276f32), (1, 0, 0, -1.0f32), (1, 223, 223, -0.011764705f32), (1, 112, 112, -0.5058824f32), (2, 0, 0, -0.75686276f32), (2, 223, 223, -0.26274508f32), (2, 112, 112, -0.5058824f32)],
    },
    Fixture {
        name: "identity_224",
        recipe: Recipe::Pattern224,
        bbox: [0.0, 0.0, 224.0, 224.0],
        crop: [0, 0, 224, 224],
        rgb8_fnv1a64: 0xCEC700D6210505E5,
        tensor_fnv1a64: 0xA7ED83836FCEC4D3,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [91, 0, 0]), (0, 223, [0, 25, 0]), (223, 223, [91, 25, 65]), (112, 112, [48, 16, 0]), (4, 0, [20, 0, 0]), (223, 112, [91, 16, 144]), (112, 223, [48, 25, 144])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, -0.2862745f32), (0, 112, 112, -0.62352943f32), (1, 0, 0, -1.0f32), (1, 223, 223, -0.8039216f32), (1, 112, 112, -0.8745098f32), (2, 0, 0, -1.0f32), (2, 223, 223, -0.49019605f32), (2, 112, 112, -1.0f32)],
    },
    Fixture {
        name: "downsample_448",
        recipe: Recipe::Pattern448,
        bbox: [0.0, 0.0, 448.0, 448.0],
        crop: [0, 0, 448, 448],
        rgb8_fnv1a64: 0x7702AB7D6EB2BCA5,
        tensor_fnv1a64: 0x8F497BC0D921B9E9,
        probes: &[(0, 0, [112, 112, 1]), (223, 0, [94, 130, 191]), (0, 223, [130, 94, 191]), (223, 223, [112, 112, 1]), (112, 112, [112, 112, 1]), (4, 0, [120, 104, 9]), (223, 112, [126, 162, 95]), (112, 223, [162, 126, 95])],
        tensor_probes: &[(0, 0, 0, -0.12156862f32), (0, 223, 223, -0.12156862f32), (0, 112, 112, -0.12156862f32), (1, 0, 0, -0.12156862f32), (1, 223, 223, -0.12156862f32), (1, 112, 112, -0.12156862f32), (2, 0, 0, -0.99215686f32), (2, 223, 223, -0.99215686f32), (2, 112, 112, -0.99215686f32)],
    },
    Fixture {
        name: "downscale_336",
        recipe: Recipe::Pattern336,
        bbox: [0.0, 0.0, 336.0, 336.0],
        crop: [0, 0, 336, 336],
        rgb8_fnv1a64: 0x7B89273152DCAA45,
        tensor_fnv1a64: 0x0877CDDC9E034215,
        probes: &[(0, 0, [8, 8, 2]), (223, 0, [104, 22, 235]), (0, 223, [22, 104, 137]), (223, 223, [117, 117, 102]), (112, 112, [88, 88, 178]), (4, 0, [74, 146, 19]), (223, 112, [128, 78, 163]), (112, 223, [78, 128, 117])],
        tensor_probes: &[(0, 0, 0, -0.9372549f32), (0, 223, 223, -0.082352936f32), (0, 112, 112, -0.3098039f32), (1, 0, 0, -0.9372549f32), (1, 223, 223, -0.082352936f32), (1, 112, 112, -0.3098039f32), (2, 0, 0, -0.9843137f32), (2, 223, 223, -0.19999999f32), (2, 112, 112, 0.39607847f32)],
    },
    Fixture {
        name: "constant_rgb_channels",
        recipe: Recipe::Steps,
        bbox: [8.0, 8.0, 24.0, 24.0],
        crop: [0, 0, 37, 37],
        rgb8_fnv1a64: 0xD03FB0034EAD8B13,
        tensor_fnv1a64: 0xA7C189BB6C2A94D6,
        probes: &[(0, 0, [0, 0, 0]), (223, 0, [0, 0, 0]), (0, 223, [0, 0, 0]), (223, 223, [0, 0, 0]), (112, 112, [255, 255, 0]), (4, 0, [0, 0, 0]), (223, 112, [0, 255, 255]), (112, 223, [255, 0, 255])],
        tensor_probes: &[(0, 0, 0, -1.0f32), (0, 223, 223, -1.0f32), (0, 112, 112, 1.0f32), (1, 0, 0, -1.0f32), (1, 223, 223, -1.0f32), (1, 112, 112, 1.0f32), (2, 0, 0, -1.0f32), (2, 223, 223, -1.0f32), (2, 112, 112, -1.0f32)],
    },
    Fixture {
        name: "face_roi_300x260",
        recipe: Recipe::Camera640,
        bbox: [254.0, 170.0, 364.5, 265.75],
        crop: [159, 87, 459, 347],
        rgb8_fnv1a64: 0xFEFCE19479E6EB76,
        tensor_fnv1a64: 0xF640443295ED317B,
        probes: &[(0, 0, [119, 196, 173]), (223, 0, [161, 119, 250]), (0, 223, [138, 186, 171]), (223, 223, [181, 88, 238]), (112, 112, [163, 196, 140]), (4, 0, [188, 110, 225]), (223, 112, [47, 135, 112]), (112, 223, [41, 56, 14])],
        tensor_probes: &[(0, 0, 0, -0.06666666f32), (0, 223, 223, 0.41960788f32), (0, 112, 112, 0.27843142f32), (1, 0, 0, 0.5372549f32), (1, 223, 223, -0.3098039f32), (1, 112, 112, 0.5372549f32), (2, 0, 0, 0.35686278f32), (2, 223, 223, 0.8666667f32), (2, 112, 112, 0.09803927f32)],
    },
    Fixture {
        name: "full_frame_640x480",
        recipe: Recipe::Camera640,
        bbox: [0.0, 0.0, 640.0, 480.0],
        crop: [0, 0, 640, 480],
        rgb8_fnv1a64: 0xE31D750E0DBC9801,
        tensor_fnv1a64: 0x4AAD2534012939D8,
        probes: &[(0, 0, [16, 0, 3]), (223, 0, [107, 45, 249]), (0, 223, [33, 55, 225]), (223, 223, [124, 150, 27]), (112, 112, [224, 179, 115]), (4, 0, [165, 1, 49]), (223, 112, [233, 97, 9]), (112, 223, [97, 146, 97])],
        tensor_probes: &[(0, 0, 0, -0.8745098f32), (0, 223, 223, -0.027450979f32), (0, 112, 112, 0.75686276f32), (1, 0, 0, -1.0f32), (1, 223, 223, 0.17647064f32), (1, 112, 112, 0.4039216f32), (2, 0, 0, -0.9764706f32), (2, 223, 223, -0.7882353f32), (2, 112, 112, -0.09803921f32)],
    },
    Fixture {
        name: "clipped_roi_521x463",
        recipe: Recipe::Camera640,
        bbox: [290.5, 188.5, 490.5, 388.5],
        crop: [119, 17, 640, 480],
        rgb8_fnv1a64: 0xE251F914659046D5,
        tensor_fnv1a64: 0x68A8DF82DC16A12F,
        probes: &[(0, 0, [142, 125, 207]), (223, 0, [229, 118, 232]), (0, 223, [41, 75, 14]), (223, 223, [128, 124, 27]), (112, 112, [29, 58, 249]), (4, 0, [16, 26, 20]), (223, 112, [57, 155, 7]), (112, 223, [99, 189, 23])],
        tensor_probes: &[(0, 0, 0, 0.11372554f32), (0, 223, 223, 0.003921628f32), (0, 112, 112, -0.77254903f32), (1, 0, 0, -0.019607842f32), (1, 223, 223, -0.027450979f32), (1, 112, 112, -0.54509807f32), (2, 0, 0, 0.62352943f32), (2, 223, 223, -0.7882353f32), (2, 112, 112, 0.9529412f32)],
    },
];

pub(super) struct CropFixture {
    pub name: &'static str,
    /// Frame width and height.
    pub frame: (u32, u32),
    pub bbox: [f32; 4],
    /// Half-open [x1, y1, x2, y2] from the scorer's float32 expansion.
    pub crop: [i32; 4],
    /// The same expansion in float64, which the contract rejects.
    pub crop_float64: [i32; 4],
}

pub(super) const CROP_FIXTURES: &[CropFixture] = &[
    CropFixture {
        name: "f32_margin_left_bound",
        frame: (640, 480),
        bbox: [202.2857, 120.0, 263.2857, 181.0],
        crop: [150, 67, 315, 233],
        crop_float64: [149, 67, 315, 233],
    },
    CropFixture {
        name: "f32_margin_right_bound",
        frame: (640, 480),
        bbox: [288.5714, 120.0, 348.5714, 180.0],
        crop: [237, 68, 400, 231],
        crop_float64: [237, 68, 399, 231],
    },
];

pub(super) struct WrapCase {
    pub name: &'static str,
    pub recipe: Recipe,
    pub bbox: [f32; 4],
    /// Width and height of the non-empty chip the scorer slices.
    pub scorer_chip_wh: [usize; 2],
}

pub(super) const SCORER_WRAP_CASES: &[WrapCase] = &[
    WrapCase {
        name: "negative_stop_left_of_frame",
        recipe: Recipe::Camera640,
        bbox: [-300.0, 100.0, -200.0, 200.0],
        scorer_chip_wh: [526, 271],
    },
    WrapCase {
        name: "negative_width",
        recipe: Recipe::Camera640,
        bbox: [10.0, 100.0, -10.0, 200.0],
        scorer_chip_wh: [586, 271],
    },
];
